build: auto refresh dist/ for dependabot (#70)

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -25,6 +25,9 @@ jobs:
     name: Check dist/
     runs-on: ubuntu-latest
 
+    outputs:
+      commit_diff: ${{ steps.diff.outputs.commit_diff }}
+
     steps:
       - name: Checkout
         id: checkout
@@ -45,22 +48,93 @@ jobs:
         id: build
         run: npm run bundle
 
-      # This will fail the workflow if the PR wasn't created by Dependabot.
-      - name: Compare Directories
+      # Check if there are differences
+      - name: Check for differences
         id: diff
+        env:
+          IS_DEPENDABOT:
+            ${{ github.event.pull_request && github.actor == 'dependabot[bot]'
+            && 'true' || 'false' }}
         run: |
           if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build. See status below:"
-            git diff --ignore-space-at-eol --text dist/
-            exit 1
+            echo "has_diff=true" | tee -a $GITHUB_OUTPUT
+            if [ "$IS_DEPENDABOT" = "true" ]; then
+              echo "commit_diff=true" | tee -a $GITHUB_OUTPUT
+            else
+              echo "fail_diff=true" | tee -a $GITHUB_OUTPUT
+            fi
           fi
+
+      # This will fail the workflow if the PR wasn't created by Dependabot.
+      - name: Fail on differences
+        if: ${{ steps.diff.outputs.fail_diff == 'true' }}
+        id: fail-diff
+        run: |
+          echo "Detected uncommitted changes after build. See status below:"
+          git diff --ignore-space-at-eol --text dist/
+          exit 1
 
       # If `dist/` was different than expected, and this was not a Dependabot
       # PR, upload the expected version as a workflow artifact.
-      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload Artifact
+      - name: Upload on differences
+        if: ${{ always() && steps.diff.outputs.has_diff == 'true' }}
         id: upload
         uses: actions/upload-artifact@v4
         with:
           name: dist
           path: dist/
+
+  commit-dist:
+    name: Commit dist/
+    runs-on: ubuntu-latest
+
+    needs: check-dist
+    if: needs.check-dist.outputs.commit_diff == 'true'
+
+    steps:
+      - name: Create application token
+        uses: actions/create-github-app-token@v2
+        id: app-token
+        with:
+          app-id: ${{ secrets.OMNICLI_APP_ID }}
+          private-key: ${{ secrets.OMNICLI_PRIVATE_KEY }}
+
+      - name: Checkout commit
+        uses: actions/checkout@v4
+        with:
+          token: ${{ steps.app-token.outputs.token }}
+
+      - name: Download dist/ artifact from check-dist job
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+
+      - name: Craft commit message
+        run: |
+          echo "chore: update dist/ directory" | tee commit.txt
+
+      - name: git commit
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add ./dist
+          git commit --no-verify --file=commit.txt
+
+      - name: git push
+        env:
+          HEAD_REF: ${{ github.head_ref }}
+        run: |
+          git push --no-verify --force "HEAD:${HEAD_REF}"
+
+  fail-after-commit:
+    name: Fail after commit
+    runs-on: ubuntu-latest
+
+    needs: commit-dist
+    if: needs.commit-dist.result == 'success'
+
+    steps:
+      - name: Fail workflow
+        run: |
+          echo "The dist/ directory was updated. Changes need to pass the tests before merging."
+          exit 1
