add CI tests running the action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,8 +44,8 @@ jobs:
         id: npm-ci-test
         run: npm run ci-test
 
-  test-action:
-    name: GitHub Actions Test
+  test-action-success:
+    name: GitHub Action Test
     runs-on: ubuntu-latest
 
     steps:
@@ -67,3 +67,60 @@ jobs:
       - name: Print Output
         id: output
         run: echo "${{ toJSON(steps.test-action.outputs) }}"
+
+  test-action-up-error:
+    name: GitHub Action Test (failing 'omni up')
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Create empty git repository
+        run: |
+          git init
+          cat >.omni.yaml <<EOF
+          up:
+            - ThisIsNotASupportedTool
+          EOF
+
+      - name: Test Local Action
+        id: test-action
+        continue-on-error: true
+        uses: ./
+        with:
+          up: true
+
+      - name: Check if action errored
+        env:
+          ACTION_OUTCOME: ${{ steps.test-action.outcome }}
+        run: |
+          if [[ "$ACTION_OUTCOME" == "success" ]]; then
+            echo "Action did not error"
+            exit 1
+          fi
+
+  test-action-check-error:
+    name: GitHub Action Test (failing 'omni config check')
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Create empty git repository
+        run: |
+          git init
+          cat >.omni.yaml <<EOF
+          up: false  # Should be an object, the check should complain
+          EOF
+
+      - name: Test Local Action
+        id: test-action
+        continue-on-error: true
+        uses: ./
+        with:
+          check: true
+
+      - name: Check if action errored
+        env:
+          ACTION_OUTCOME: ${{ steps.test-action.outcome }}
+        run: |
+          if [[ "$ACTION_OUTCOME" == "success" ]]; then
+            echo "Action did not error"
+            exit 1
+          fi
