throw clear error on failure and store it

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -98,9 +98,15 @@ jobs:
       - name: Check if action errored
         env:
           ACTION_OUTCOME: ${{ steps.test-action.outcome }}
+          ACTION_ERROR: ${{ steps.test-action.outputs.error }}
         run: |
           if [[ "$ACTION_OUTCOME" == "success" ]]; then
             echo "Action did not error"
+            exit 1
+          fi
+
+          if [[ "$ACTION_ERROR" != "omni up "*" failed with exit code 1" ]]; then
+            echo "Action did not error with the expected error message"
             exit 1
           fi
 
@@ -133,8 +139,14 @@ jobs:
       - name: Check if action errored
         env:
           ACTION_OUTCOME: ${{ steps.test-action.outcome }}
+          ACTION_ERROR: ${{ steps.test-action.outputs.error }}
         run: |
           if [[ "$ACTION_OUTCOME" == "success" ]]; then
             echo "Action did not error"
+            exit 1
+          fi
+
+          if [[ "$ACTION_ERROR" != "omni config check "*" failed with exit code 1" ]]; then
+            echo "Action did not error with the expected error message"
             exit 1
           fi
